version: "2"
run:
  go: 1.25.5
linters:
  # Disable all linters by default.
  # Default: false
  default: none
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - go.uber.org/multierr
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    mnd:
      # don't include the "operation" and "assign"
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
      ignored-functions:
        - strings.SplitN
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: false # don't require an explanation for nolint directives
      require-specific: false # don't require nolint directives to be specific about which linter is being skipped
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - depguard
          - goimports
          - mnd
          - revive
        path: _test\.go
      - linters:
          - depguard
          - mnd
          - revive
        path: _test\.go
      - path: db_test.go
        text: 'deferInLoop: Possible resource leak, ''defer'' is called in the ''for'' loop'
      - path: \.go
        text: 'commentedOutCode: may want to remove commented-out code'
      - path: \.go
        text: 'commentFormatting: put a space between `//` and comment text'
      - linters:
          - whitespace
        path: _test.go
        text: unnecessary (leading|trailing) newline
      - linters:
          - errcheck
          - funlen
          - goconst
          - gocritic
          - gocyclo
          - govet
        path: db_test.go
      - linters:
          - errcheck
          - funlen
          - goconst
          - gocritic
          - gocyclo
          - govet
        path: fuzz_test.go
      - path: \.go
        text: 'G404: Use of weak random number generator' #expected, just for randomLB policy
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
